### PR TITLE
Basic submission system for variations

### PR DESCRIPTION
**Pull request by dipamsen**
- Added info to readme about variations
- Added "Variations" section on readme which will list all variations
- Created PR Template for submission

This includes a very crude submission system by including the title, url and image inside the readme itself.

image

We will eventually want to move to a more streamlined system (JSON + site), but maybe this can be used for now to accept variations?

### CODE REVIEW

**Comment by shiffman** [comment]
This looks great! Apologies for introducing merge conflicts. Should we make the image optional and/or include some basic instructions for how to upload with the pull request?

**Comment by dipamsen** [comment]
Reorganised the files, and marked image as optional. We can create a Contributing file with info on creating a PR, but I think this can be merged for now.

**Comment by shiffman** [comment]
haha, sorry, i did it again!

**Comment by dipamsen** [comment]
Fixed!

**Comment by shiffman** [comment]
woohoo!

**Pull request merged**
